/* les fichiers sont lus depuis CE dépôt (pas depuis un autre dossier) */
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const RACINE = join(dirname(fileURLToPath(import.meta.url)), '..');
import { JSDOM, VirtualConsole } from 'jsdom'; import fs from 'fs'; import http from 'node:http'; import { Readable } from 'node:stream';
const BASE='http://127.0.0.1:8080/';
function nodeFetch(url,o={}){return new Promise((res,rej)=>{const u=new URL(url);const r=http.request({hostname:u.hostname,port:u.port,path:u.pathname+u.search,method:o.method||'GET'},x=>res(new Response(Readable.toWeb(x),{status:x.statusCode,headers:x.headers})));r.on('error',rej);r.end();});}
const vc=new VirtualConsole(); const errs=[]; vc.on('jsdomError',e=>errs.push(e.message));
const dom=new JSDOM(fs.readFileSync(join(RACINE, 'index.html'),'utf8'),{url:BASE,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});
const {window}=dom;
window.fetch=(u,o)=>nodeFetch(new URL(u,BASE).href,o);
window.DecompressionStream=DecompressionStream;window.Response=Response;window.Headers=Headers;window.Request=Request;
window.caches={open:async()=>({match:async()=>null,put:async()=>{}}),keys:async()=>[],delete:async()=>{}};
window.navigator.clipboard={writeText:async()=>{}};
window.IntersectionObserver=class{constructor(cb){this.cb=cb}observe(){}unobserve(){}disconnect(){}};
window.navigator.storage={estimate:async()=>({usage:1e6,quota:1e9})};
window.matchMedia=window.matchMedia||(()=>({matches:false,addListener(){},removeListener(){}}));
const sc=window.document.createElement('script'); sc.textContent=fs.readFileSync(join(RACINE, 'app.js'),'utf8'); window.document.body.appendChild(sc);
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); await sleep(3000);
const $=s=>window.document.querySelector(s), $$=s=>[...window.document.querySelectorAll(s)];
console.log('— Accueil —');
console.log(' stats:', $('#stats').textContent.replace(/\s+/g,' ').trim());
console.log(' tuile VGR:', $('#tileVgrS')?.textContent);
console.log(' tuile prédications:', $('#tileSermons')?.textContent.slice(0,150));
console.log('\n— Filtre « La Voix de Dieu — tout » —');
const chip=$$('#chipsTrad .chip').find(c=>c.dataset.trad==='VGR-OFF');
chip.dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
await sleep(400);
console.log(' compteur:', $('#sermonCount').textContent);
const items=$$('#sermonList .item').slice(0,3).map(i=>i.textContent.replace(/\s+/g,' ').trim().slice(0,95));
items.forEach(i=>console.log('   ·',i));
console.log('\n— Filtre « officiel » uniquement —');
$$('#chipsTrad .chip').find(c=>c.dataset.trad==='VGR-OFF').dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
await sleep(400);
console.log(' compteur:', $('#sermonCount').textContent, '| badge:', $$('#sermonList .item .badge')[0]?.textContent);
console.log('\n— Ouverture d\'une brochure VGR officielle —');
const first=$$('#sermonList .item')[0];
first.dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
await sleep(2500);
console.log(' titre:', $('#rhTitle').textContent);
console.log(' méta:', $('#rhMeta').textContent.slice(0,110));
console.log(' paragraphes:', $$('#sermonBody p').length);
console.log(' extrait:', $$('#sermonBody p')[1]?.textContent.slice(0,150));
console.log(' PDF:', ($('#btnPdf').getAttribute('href')||'').slice(0,80));
console.log(' audio:', ($('#btnMp3').getAttribute('href')||'').slice(0,70));
console.log('\n— Recherche approfondie (VGR inclus) —');
window.eval("state.cat.sermons = state.cat.sermons.filter(r=>r.trad==='VGR-OFF').slice(0,40); state.sermons=state.cat.sermons;");
$$('[data-go]').find(b=>b.dataset.go==='search').dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
await sleep(300); $('#deepQ').value='colombe'; $('#deepGo').dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
for(let i=0;i<30 && !/textes lus/.test($('#deepStatus').textContent);i++) await sleep(1000);
console.log(' ', $('#deepStatus').textContent, '| résultats:', $$('#deepResults .item').length);
console.log('\nErreurs JS:', errs.filter(e=>!/scrollTo|not implemented/i.test(e)).slice(0,4));
